### ISSUE TITLE
Db.getCards() throwing exception

### ISSUE THREAD

**Issue by m-krajcovic** [nasajoey/Java-API-to-mtgdb#11]
This is what i get after calling Db.getCards(). Any way to fix this?

```
Exception in thread "main" org.json.JSONException: JSONObject["releasedAt"] not a string.
    at org.json.JSONObject.getString(JSONObject.java:658)
    at info.mtgdb.api.Card.<init>(Card.java:138)
    at info.mtgdb.api.Db.getCardsFromUrl(Db.java:108)
    at info.mtgdb.api.Db.getCards(Db.java:313)
```

**Comment by alotau** [comment]
Yo, Zoidby!  Why did you close the issue?  I was working on it and got it fixed.  Let me know if you still have problems.
